# Generated by Django 3.2.6 on 2021-09-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210905_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images\\profile1.png', null=True, upload_to=''),
        ),
    ]
